docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - umask 0022
    - chmod -R og-w .
    - docker build -t jgoerzen/tor .
    - docker tag jgoerzen/tor jgoerzen/tor:bookworm
    - docker push jgoerzen/tor
    - docker push jgoerzen/tor:bookworm
  only:
    - master
